### ISSUE TITLE
Can't Get Downloader working

### ISSUE THREAD

**Issue by Zurriel599** [Emersont1/itchio#59]
I can't seem to get the downloader working, I got the bundle tool to add all my games to my library. When I start a download I get this window, it looks like it is downloading but no files or folders are made anywhere on my computer. I have tried Python 3.8 as I saw it was stable in a Reddit post and I have tried 3.10 as well. I even tried a different computer in case it was an issue with Windows 11. I have also tried using the API key as well. Is there something I am not doing?
![2022-07-09 09_53_15-Command Prompt](https://user-images.githubusercontent.com/25692577/178108790-7ee4a7b7-cf47-4f5a-8980-3879c400eb87.png)

**Comment by Zurriel599** [comment]
I have found it is downloading the folders to the C:\Users\Username directory on Windows, Some folders have the JSON files inside but I don't see any of the games downloaded. Is this normal behavior?

**Comment by Zurriel599** [comment]
Hey there, I saw you did the update ten days ago, I am still having the same problems on a new system. Is there a step I'm missing thats not in the readme? I have tried PIP and running the files manually in an IDE. I know Python 101 but I am not an expert, any help would be appreciated. 

I can get to start the download, it makes a whole bunch of empty folders then nothing.

**Comment by Emersont1** [comment]
It should be fixed now if you download the 2.1.2 version

**Comment by Stat1c-V01D** [comment]
Issue still persists even with the newest version. Somehow the parsed HTML data does not include the "span pager_label a". 
After a couple of tries I am also getting Response 404 out of self.login.get(). This might be because of intensive testing. I'll try again in a little while.

**Comment by Shashwat-05** [comment]
Similar issue, no progress after running the tool
![image](https://user-images.githubusercontent.com/71658650/208231275-41a44165-793e-483d-acc9-efe6ccd994f1.png)
